### ISSUE TITLE
Is there any tutorials for ajoke on osx?

### ISSUE THREAD

**Issue by DogLooksGood** [baohaojun/ajoke#14]
I tried it on osx, and find `mkgtags` script doesn't work, caused by some difference between GNU readlink and readlink on osx.
BTW, is there any idea to develop a Java layer for spacemacs?

**Comment by baohaojun** [comment]
Hi, you are right, I myself would use readlink from MacPorts instead of the system default. I have another github project ``system-config'', which try to make all systems (Linux, Mac, Windows) easy to configure and give an almost same UX, and Mac is really difficult to setup because I don't know which one to go, MacPorts or HomeBrew? And both seem to be missing a mirror in China, which means it's very slow for me to install either one. Even cygwin is better in this respect.. So, I've not use Mac very much, am a major Linux guy:-)

BTW,  have switched from gtags to using beagrep for making tags and lookup, it's a lot faster.

No, I have no idea how to develop Java layer for spacemacs, hope ajoke works for it though:-)
